name: heroku-jupyter
dependencies:
  - gcc
  - pip:
    - pgcontents
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
    - pymc3
    - git+https://github.com/quantopian/alphalens
    # - scikit-cuda
  # bind notebook version (compatibility to pgcontents)
  - notebook = 4
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython = 5
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - numpy
  - scipy
  - theano
  - matplotlib
  - pandas
  # - pygpu
