name: heroku-jupyter
dependencies:
#  - python=2.7
  # bind notebook version (compatibility to pgcontents)
  - notebook = 4
  - ipywidgets
  - requests
  # bind ipython version (compatibility to pgcontents)
  - ipython = 5
  # get dependencies for pgcontents
  - certifi
  - click
  - cryptography
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip:
    - pgcontents
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git
    - pymc3
  - numpy=1.11.1
  - scipy=0.18.1
  - theano=0.9.0
  - matplotlib=2.0.0
  - pandas=0.18.1
